sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 10.15.3
branches:
  only:
    - master
notifications:
  email: false
script:
  - yarn run validate
#after_success:
#- yarn run test:coverage
